### ISSUE TITLE
Сломан трекер

### ISSUE THREAD

**Issue by alting** [turbo-lab/pandora#1]
Трекер не работает в 0.106.2:
2020-03-01 11:49:47 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
File “/usr/lib/python3.7/concurrent/futures/thread.py”, line 57, in run
result = self.fn(*self.args, **self.kwargs)
File “/home/homeassistant/.homeassistant/custom_components/pandora/init.py”, line 140, in update
listener()
File “/home/homeassistant/.homeassistant/custom_components/pandora/device_tracker.py”, line 55, in update
if self.vehicle.state.bit_state_1 & 1 == 1:
TypeError: unsupported operand type(s) for &: ‘str’ and ‘int’

Соответственно, никакая информация не обновляется.
Linux raspberrypi4 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
HA установлен в venv.

**Comment by turbo-lab** [comment]
Fixed in 1ade6597d4a61120096c47e6c7b0068f28fcb402
